
CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA (
 IdEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeEmpresa VARCHAR(30) NOT NULL
);
GO

CREATE TABLE MARCA (
 IdMarca TINYINT PRIMARY KEY IDENTITY(1,1),
 nomeMarca VARCHAR(20) NOT NULL
);
GO


CREATE TABLE MODELO (
 IdModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
 IdMarca TINYINT FOREIGN KEY REFERENCES MARCA(IdMarca),
 descriçãoModelo VARCHAR(30) NOT NULL

);
GO



--SALVAR

CREATE TABLE Cliente (
 IdCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeCliente VARCHAR(30) NOT NULL,
 cpfCliente CHAR(11) NOT NULL
);
GO

CREATE TABLE ALUGUEL (
 IdAluguel INT PRIMARY KEY IDENTITY(1,1),
 IdVeiculo SMALLINT FOREIGN KEY REFERENCES EMPRESA(IdEmpresa),
 IdCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(IdCliente),
 valor VARCHAR(2000) NOT NULL,
 dataAluguelInicio VARCHAR(20) NOT NULL,
 dataAluguelFim VARCHAR(20) NOT NULL,

);
GO


CREATE TABLE VEICULO (
 IdVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
 IdModelo SMALLINT FOREIGN KEY REFERENCES MODELO(IdModelo),
 placa CHAR(7) 

);
GO

--SOLUÇÃO
DROP DATABASE LOCADORA



--DELETAR COLUNA
--DELETE FROM ALUGUEL
--WHERE IdCliente IS NULL