CREATE DATABASE T_Rental;
GO

USE T_Rental;
GO

CREATE TABLE EMPRESA (
idEmpresa TINYINT PRIMARY KEY IDENTITY (1,1),
empresa VARCHAR (50) NOT NULL
);
GO


 CREATE TABLE MARCA(
 IdMarca SMALLINT PRIMARY KEY IDENTITY (1,1),
 Marca VARCHAR(50) NOT NULL
 );
GO

 CREATE TABLE MODELO(
 IdModelo SMALLINT PRIMARY KEY IDENTITY (1,1),
 IdMarca SMALLINT FOREIGN KEY REFERENCES Marca(idMarca),
 modelo VARCHAR(30) NOT NULL
 );
 GO

 CREATE TABLE VEICULO(
 IdVeiculo SMALLINT PRIMARY KEY IDENTITY (1,1),
 IdEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA (idEmpresa),
 IdModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
 placaVeiculo CHAR(7) NOT NULL
 );
GO

  CREATE TABLE CLIENTE(
 IdCliente SMALLINT PRIMARY KEY IDENTITY (1,1),
 nomeCliente VARCHAR(30) NOT NULL,
 sobrenomeCliente VARCHAR(30) NOT NULL,
 cnpjCliente CHAR(15) NOT NULL
 );
 GO
 
 CREATE TABLE ALUGUEL(
 IdAluguel SMALLINT PRIMARY KEY IDENTITY (1,1),
 IdVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
 IdCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
 Aluguel DATETIME NOT NULL,
 Devolucao DATETIME NOT NULL
 );
GO

Drop table ALUGUEL
 



 DROP DATABASE T_RENTAL


