CREATE DATABASE HROADS_NP;
GO

USE HROADS_NP;
GO
 
 CREATE TABLE CLASSE(
 idClasse SMALLINT PRIMARY KEY IDENTITY (1,1),
 descricaoClasse VARCHAR(40) NOT NULL,
 );
 GO

 CREATE TABLE TIPOHABILIDADE(
 idTipo SMALLINT PRIMARY KEY IDENTITY (1,1),
 descricaoTipo VARCHAR(20) NOT NULL,
 );
 GO

CREATE TABLE PERSONAGEM(
idPersonagem SMALLINT PRIMARY KEY IDENTITY(1,1),
idClasse SMALLINT FOREIGN KEY REFERENCES CLASSE (idClasse),
nomePersonagem VARCHAR(40) NOT NULL,
capacidadeMax VARCHAR(5),
capacidadeMana VARCHAR(5),
dataAtualizacao DATETIME,
dataCriacao CHAR(10) NOT NULL
);
GO
 
 CREATE TABLE HABILIDADE(
 idHabilidade SMALLINT PRIMARY KEY IDENTITY (1,1),
 idTipo SMALLINT FOREIGN KEY REFERENCES TIPOHABILIDADE (idTipo),
 nomeHabilidade VARCHAR(40) NOT NULL,
 );
 GO

CREATE TABLE CLASSE_HABILIDADE(
 idClasse SMALLINT FOREIGN KEY REFERENCES CLASSE (idClasse),
 idHabilidade SMALLINT FOREIGN KEY REFERENCES HABILIDADE (idHabilidade),
 );
 GO 

  CREATE TABLE TIPOUSARIO(
 idTipoUsuario SMALLINT PRIMARY KEY IDENTITY (1,1),
 titulo VARCHAR(40) NOT NULL,
 );
 GO


 CREATE TABLE USUARIO(
 idUsuario SMALLINT PRIMARY KEY IDENTITY (1,1),
 idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPOUSARIO (idTipoUsuario),
 email VARCHAR(150) NOT NULL UNIQUE,
 nome VARCHAR(180) NOT NULL,
 senha VARCHAR(30) NOT NULL,
 );
 GO




