


CREATE DATABASE OPCUSEX
GO

USE OPCUSEX
GO

CREATE TABLE USUARIO(
IdUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeUsuario VARCHAR(15) NOT NULL,
email VARCHAR(256) NOT NULL,
cpf VARCHAR(10) NOT NULL,
senha VARCHAR(10) NOT NULL,
tipodePermissao VARCHAR(10) NOT NULL
);
GO

CREATE TABLE ARTISTAS(
IdArtistas SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeArtistas VARCHAR(50) NOT NULL,
);
GO

CREATE TABLE ESTILOMUSICAL(
IdEstMusical SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeEstMusical VARCHAR(20) NOT NULL
);
GO

CREATE TABLE EMPRESA(
IdEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
IdUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(IdUsuario),
nomeEmpresa VARCHAR(50) NOT NULL
);
GO

CREATE TABLE CD(
IdCD SMALLINT PRIMARY KEY IDENTITY(1,1),
IdArtistas SMALLINT FOREIGN KEY REFERENCES ARTISTAS(IdArtistas),
IdEstMusical SMALLINT FOREIGN KEY REFERENCES ESTILOMUSICAL(IdEstMusical),
nomeCD VARCHAR(50) NOT NULL
);
GO

CREATE TABLE ALBUM(
IdALBUM SMALLINT PRIMARY KEY IDENTITY(1,1),
IdArtistas SMALLINT FOREIGN KEY REFERENCES ARTISTAS(IdArtistas),
IdEstMusical SMALLINT FOREIGN KEY REFERENCES ESTILOMUSICAL(IdEstMusical),
nomeCD VARCHAR(50) NOT NULL
);
GO

ALTER TABLE ALBUM
DROP COLUMN nomeCD

ALTER TABLE ALBUM
ADD nomeAlbum VARCHAR(50) NOT NULL

ALTER TABLE ALBUM
ADD lançamento DATE

ALTER TABLE ALBUM
ADD quantMin VARCHAR(10) 

ALTER TABLE ALBUM
ADD Localização VARCHAR(50) 

ALTER TABLE ALBUM
ADD Visualização VARCHAR(15) 
